import type { ModelCapabilities, ModelInfo } from '@studio/core';

/**
 * Offline-Startkatalog. Wird nach `ModelRegistry.sync()` durch Live-Daten (Beschreibung, Preis, Fähigkeiten aus dem
 * Schema) überschrieben; kuratierte Felder (`recommended`, Zusatzfähigkeiten, Hinweise) bleiben erhalten.
 *
 * Quellen: Endpoint-IDs und Parameter aus den Typen von `@fal-ai/client` 1.10.1 (`src/types/endpoints.d.ts`) bzw. –
 * für die h3-max-Familie, die dort noch fehlt – aus fal-Modellseiten (Suchsnippets) und dem Open-Source-Code von
 * pollinations (minimaxH3Model.ts). Preise stammen aus Suchsnippets der fal-Modellseiten und sind als ungeprüft markiert.
 */

const PRICE_DATE = '2026-10-01';
const UNVERIFIED = `Preis Stand ${PRICE_DATE} (Websuche), ungeprüft.`;
const TAG_UNVERIFIED = 'preis-ungeprüft';
const TAG_SEED = 'seed';

const range = (from: number, to: number): number[] => Array.from({ length: to - from + 1 }, (_, i) => from + i);

const H3_RATIOS = ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'];
const H3_RESOLUTIONS = ['480P', '768P', '1080P'];
const H3_CAPS: ModelCapabilities = { nativeAudio: true, durations: range(5, 15), maxDurationSec: 15, resolutions: H3_RESOLUTIONS, seed: true };

function seed(entry: Omit<ModelInfo, 'provider'> & { provider?: ModelInfo['provider'] }): ModelInfo {
  const tags = [...new Set([TAG_SEED, ...(entry.tags ?? []), ...(entry.price ? [TAG_UNVERIFIED] : [])])];
  const description = entry.price ? `${entry.description} ${UNVERIFIED}` : entry.description;
  return { provider: 'fal', ...entry, description, tags };
}

export const SEED_MODELS: ModelInfo[] = [
  // ───────────── Video: h3-max-Familie (Default) ─────────────
  seed({
    id: 'minimax/h3-max/text-to-video',
    modality: 'video',
    category: 'text-to-video',
    displayName: 'H3 Max',
    vendor: 'MiniMax · fal',
    description:
      'Standard-Videomodell (von fal nachtrainiertes MiniMax H3): Text → Video mit nativer Tonspur, 5–15 s (ganze Sekunden), 24 fps, 480P/768P/1080P, Formate 21:9–9:16, kein 4:5 (→ Reframing/Outpainting). Je Sekunde: 480P $0.05, 768P $0.08, 1080P $0.16.',
    price: { unitPrice: 0.08, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, aspectRatios: H3_RATIOS },
    recommended: true,
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max/image-to-video',
    modality: 'video',
    category: 'image-to-video',
    displayName: 'H3 Max · Bild → Video',
    vendor: 'MiniMax · fal',
    description: 'H3 Max mit Startbild (`image_url`) und optionalem Endbild (`end_image_url`); Seitenverhältnis folgt dem Bild. 5–15 s mit Tonspur.',
    price: { unitPrice: 0.08, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, imageInput: true },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max/reference-to-video',
    modality: 'video',
    alsoModalities: ['lipsync'],
    category: 'image-to-video',
    displayName: 'H3 Max · Referenzen → Video',
    vendor: 'MiniMax · fal',
    description:
      'H3 Max mit Referenzen (`reference_image_urls`, `reference_video_urls`, `reference_audio_urls`); der Prompt verweist auf die Dateien nach Art und Position. Für Charakter-Konsistenz und audiogetriebene Shots.',
    price: { unitPrice: 0.08, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, aspectRatios: H3_RATIOS, imageInput: true, multiImageInput: true, videoInput: true, audioInput: true },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max/extend-video',
    modality: 'video',
    category: 'video-to-video',
    displayName: 'H3 Max · Video verlängern',
    vendor: 'MiniMax · fal',
    description: 'Verlängert ein Video (`video_url`, 1,6–60 s, ≤ 50 MB) um 5–15 s; der Prompt beschreibt nur die Fortsetzung.',
    price: { unitPrice: 0.08, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, videoInput: true },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max/lip-sync/image-to-video',
    modality: 'lipsync',
    alsoModalities: ['video'],
    category: 'image-to-video',
    displayName: 'H3 Max · Lip-Sync',
    vendor: 'MiniMax · fal',
    description: 'Animiert ein Bild (`image_url`) synchron zu einer Tonspur (`audio_url`, ≥ 5 s, wird bei 14,8 s abgeschnitten).',
    capabilities: { imageInput: true, audioInput: true, maxDurationSec: 14.8 },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max/director',
    modality: 'video',
    category: 'text-to-video',
    displayName: 'H3 Max Director (Echtzeit)',
    vendor: 'MiniMax · fal',
    status: 'beta',
    description:
      'Echtzeit-Variante: ein fortlaufender Videostream mit Ton, der während der Wiedergabe neue Regieanweisungen annimmt. Läuft über WebRTC (`fal.realtime`), NICHT über die Queue-API – vom Queue-Runner nicht nutzbar.',
    capabilities: { nativeAudio: true },
    tags: ['h3-max', 'familie:h3-max', 'realtime', 'nicht-queue'],
  }),
  seed({
    id: 'minimax/h3-max-turbo/text-to-video',
    modality: 'video',
    category: 'text-to-video',
    displayName: 'H3 Max Turbo',
    vendor: 'MiniMax · fal',
    description: 'Schnellere, halb so teure H3-Max-Variante für Entwürfe und Animatics. Je Sekunde: 480P $0.025, 768P $0.04, 1080P $0.08.',
    price: { unitPrice: 0.04, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, aspectRatios: H3_RATIOS },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'minimax/h3-max-turbo/image-to-video',
    modality: 'video',
    category: 'image-to-video',
    displayName: 'H3 Max Turbo · Bild → Video',
    vendor: 'MiniMax · fal',
    description: 'Turbo-Variante mit Startbild (`image_url`, optional `end_image_url`).',
    price: { unitPrice: 0.04, unit: 'seconds', currency: 'USD' },
    capabilities: { ...H3_CAPS, imageInput: true },
    tags: ['h3-max', 'familie:h3-max'],
  }),
  seed({
    id: 'fal-ai/veo3.1',
    modality: 'video',
    category: 'text-to-video',
    displayName: 'Veo 3.1',
    vendor: 'Google',
    description: 'Text → Video mit Ton, 4/6/8 s, 16:9 oder 9:16, 720p/1080p. Je Sekunde $0.40 mit Ton, $0.20 ohne (`generate_audio: false`).',
    price: { unitPrice: 0.4, unit: 'seconds', currency: 'USD' },
    capabilities: { nativeAudio: true, durations: [4, 6, 8], maxDurationSec: 8, aspectRatios: ['16:9', '9:16'], resolutions: ['720p', '1080p'], seed: true },
  }),

  // ───────────── Bild ─────────────
  seed({
    id: 'fal-ai/nano-banana-pro',
    modality: 'image',
    category: 'text-to-image',
    displayName: 'Nano Banana Pro',
    vendor: 'Google',
    description: 'Text → Bild mit sehr guter Typografie und Prompttreue; 1K/2K/4K (4K doppelter Preis), Formate 21:9–9:16 inkl. 4:5.',
    price: { unitPrice: 0.15, unit: 'images', currency: 'USD' },
    capabilities: { aspectRatios: ['21:9', '16:9', '3:2', '4:3', '5:4', '1:1', '4:5', '3:4', '2:3', '9:16'], resolutions: ['1K', '2K', '4K'], seed: true },
    recommended: true,
  }),
  seed({
    id: 'fal-ai/nano-banana-pro/edit',
    modality: 'image',
    category: 'image-to-image',
    displayName: 'Nano Banana Pro · Edit',
    vendor: 'Google',
    description: 'Bildbearbeitung und Komposition aus mehreren Referenzbildern (`image_urls`), z. B. Charakterblätter, Varianten, Collagen.',
    price: { unitPrice: 0.15, unit: 'images', currency: 'USD' },
    capabilities: {
      imageInput: true,
      multiImageInput: true,
      aspectRatios: ['21:9', '16:9', '3:2', '4:3', '5:4', '1:1', '4:5', '3:4', '2:3', '9:16'],
      resolutions: ['1K', '2K', '4K'],
      seed: true,
    },
  }),
  seed({
    id: 'fal-ai/flux-2-pro',
    modality: 'image',
    category: 'text-to-image',
    displayName: 'FLUX.2 [pro]',
    vendor: 'Black Forest Labs',
    description: 'Fotorealistische Text → Bild-Generierung; $0.03 für das erste Megapixel, $0.015 je weiteres.',
    price: { unitPrice: 0.03, unit: 'megapixels', currency: 'USD' },
    capabilities: { aspectRatios: ['1:1', '4:3', '16:9', '3:4', '9:16'], seed: true },
  }),

  // ───────────── Lipsync / Avatar ─────────────
  seed({
    id: 'fal-ai/sync-lipsync/v2',
    modality: 'lipsync',
    category: 'video-to-video',
    displayName: 'Sync Lipsync 2.0',
    vendor: 'Sync Labs',
    description: 'Lippensynchronisation eines bestehenden Videos (`video_url`) auf eine Tonspur (`audio_url`); Abrechnung je Minute Video ($3/min).',
    price: { unitPrice: 3, unit: 'minutes', currency: 'USD' },
    capabilities: { videoInput: true, audioInput: true },
    recommended: true,
  }),
  seed({
    id: 'fal-ai/kling-video/lipsync/audio-to-video',
    modality: 'lipsync',
    category: 'video-to-video',
    displayName: 'Kling LipSync (Audio → Video)',
    vendor: 'Kling',
    description: 'Lippensynchronisation über Kling; $0.014 je Sekunde Eingabevideo, aufgerundet auf 5-s-Schritte.',
    price: { unitPrice: 0.014, unit: 'seconds', currency: 'USD' },
    capabilities: { videoInput: true, audioInput: true },
  }),
  seed({
    id: 'fal-ai/bytedance/omnihuman/v1.5',
    modality: 'lipsync',
    category: 'image-to-video',
    displayName: 'OmniHuman 1.5',
    vendor: 'ByteDance',
    description: 'Audiogetriebener Avatar: animiert eine Person aus einem Bild (`image_url`) passend zu Sprache oder Gesang (`audio_url`).',
    capabilities: { imageInput: true, audioInput: true },
  }),

  // ───────────── Stimme (TTS) ─────────────
  seed({
    id: 'fal-ai/elevenlabs/tts/eleven-v3',
    modality: 'voice',
    category: 'text-to-speech',
    displayName: 'ElevenLabs Eleven v3',
    vendor: 'ElevenLabs',
    description: 'Ausdrucksstarke Sprachausgabe mit Audio-Tags, viele Sprachen inkl. Deutsch; optional Wortzeitstempel (`timestamps`). $0.10 je 1000 Zeichen.',
    price: { unitPrice: 0.1, unit: '1000 characters', currency: 'USD' },
    capabilities: { wordTimestamps: true },
    recommended: true,
  }),
  seed({
    id: 'fal-ai/elevenlabs/tts/multilingual-v2',
    modality: 'voice',
    category: 'text-to-speech',
    displayName: 'ElevenLabs Multilingual v2',
    vendor: 'ElevenLabs',
    description: 'Stabile, natürliche Mehrsprachen-Stimme für Voice-over und Erzähler; $0.10 je 1000 Zeichen.',
    price: { unitPrice: 0.1, unit: '1000 characters', currency: 'USD' },
    capabilities: { wordTimestamps: true },
  }),

  // ───────────── Musik ─────────────
  seed({
    id: 'fal-ai/elevenlabs/music',
    modality: 'music',
    category: 'text-to-audio',
    displayName: 'Eleven Music',
    vendor: 'ElevenLabs',
    description: 'Songs und Instrumentals aus Prompt oder Kompositionsplan (Abschnitte mit Dauern); Länge über `music_length_ms` (3–600 s). Ca. $0.80/min.',
    price: { unitPrice: 0.8, unit: 'minutes', currency: 'USD' },
    capabilities: { maxDurationSec: 600 },
    recommended: true,
  }),
  seed({
    id: 'fal-ai/lyria2',
    modality: 'music',
    category: 'text-to-audio',
    displayName: 'Lyria 2',
    vendor: 'Google',
    description: 'Instrumentalmusik (30-s-Clips) aus Textbeschreibung; $0.10 je Clip.',
    price: { unitPrice: 0.1, unit: 'requests', currency: 'USD' },
    capabilities: { durations: [30], maxDurationSec: 30, seed: true },
  }),
  seed({
    id: 'fal-ai/stable-audio-25/text-to-audio',
    modality: 'music',
    category: 'text-to-audio',
    displayName: 'Stable Audio 2.5',
    vendor: 'Stability AI',
    description: 'Musik und Klangflächen bis ca. 190 s (`seconds_total`).',
    capabilities: { maxDurationSec: 190, seed: true },
  }),

  // ───────────── Sound (SFX / Foley / V2A) ─────────────
  seed({
    id: 'fal-ai/elevenlabs/sound-effects/v2',
    modality: 'sound',
    category: 'text-to-audio',
    displayName: 'ElevenLabs Sound Effects v2',
    vendor: 'ElevenLabs',
    description: 'Soundeffekte aus Text, 0,5–22 s (`duration_seconds`), optional loopbar; $0.002 je Sekunde.',
    price: { unitPrice: 0.002, unit: 'seconds', currency: 'USD' },
    capabilities: { maxDurationSec: 22 },
    recommended: true,
  }),
  seed({
    id: 'fal-ai/mmaudio-v2',
    modality: 'sound',
    category: 'video-to-video',
    displayName: 'MMAudio V2 (Video → Ton)',
    vendor: 'MMAudio',
    description: 'Erzeugt passenden Ton/Foley zu einem stummen Video (`video_url`) und liefert das Video mit Tonspur.',
    capabilities: { videoInput: true, seed: true },
  }),
  seed({
    id: 'fal-ai/mmaudio-v2/text-to-audio',
    modality: 'sound',
    category: 'text-to-audio',
    displayName: 'MMAudio V2 (Text → Ton)',
    vendor: 'MMAudio',
    description: 'Geräusche und Atmos aus Text, Dauer über `duration`.',
    capabilities: { seed: true },
  }),

  // ───────────── Werkzeuge ─────────────
  seed({
    id: 'fal-ai/elevenlabs/speech-to-text/scribe-v2',
    modality: 'tools',
    category: 'speech-to-text',
    displayName: 'ElevenLabs Scribe v2 (Transkription)',
    vendor: 'ElevenLabs',
    description: 'Transkription mit Wortzeitstempeln, Sprechererkennung und Audio-Events, wortgetreu (auch Füllwörter). $0.008 je Audiominute (+30 % mit `keyterms`).',
    price: { unitPrice: 0.008, unit: 'minutes', currency: 'USD' },
    capabilities: { audioInput: true, wordTimestamps: true },
    recommended: true,
    tags: ['stt'],
  }),
  seed({
    id: 'fal-ai/whisper',
    modality: 'tools',
    category: 'speech-to-text',
    displayName: 'Whisper (Transkription)',
    vendor: 'OpenAI',
    description: 'Whisper large-v3 mit Wort-Chunks (`chunk_level: "word"`) und optionaler Diarisierung.',
    capabilities: { audioInput: true, wordTimestamps: true },
    tags: ['stt'],
  }),
  seed({
    id: 'fal-ai/wizper',
    modality: 'tools',
    category: 'speech-to-text',
    displayName: 'Wizper (schnelles Whisper v3)',
    vendor: 'fal',
    description: 'Sehr schnelle Whisper-v3-Transkription mit Segment-Zeitstempeln.',
    capabilities: { audioInput: true },
    tags: ['stt'],
  }),
  seed({
    id: 'fal-ai/demucs',
    modality: 'tools',
    category: 'audio-to-audio',
    displayName: 'Demucs (Stem-Trennung)',
    vendor: 'Meta',
    description: 'Trennt Musik in Stems (Vocals, Drums, Bass, Other; mit htdemucs_6s auch Gitarre/Piano). Ca. $0.0007 je Sekunde.',
    price: { unitPrice: 0.0007, unit: 'seconds', currency: 'USD' },
    capabilities: { audioInput: true },
    tags: ['stems'],
  }),
  seed({
    id: 'fal-ai/elevenlabs/audio-isolation',
    modality: 'tools',
    category: 'audio-to-audio',
    displayName: 'ElevenLabs Audio Isolation',
    vendor: 'ElevenLabs',
    description: 'Isoliert Sprache und entfernt Hintergrundgeräusche/Hall.',
    capabilities: { audioInput: true },
  }),
  seed({
    id: 'fal-ai/topaz/upscale/video',
    modality: 'tools',
    category: 'video-to-video',
    displayName: 'Topaz Video Upscale',
    vendor: 'Topaz Labs',
    description: 'Video-Upscaling und optionale Frame-Interpolation. Je Sekunde: bis 720p $0.01, bis 1080p $0.02, darüber $0.08 (60 fps doppelt).',
    price: { unitPrice: 0.02, unit: 'seconds', currency: 'USD' },
    capabilities: { videoInput: true },
    tags: ['upscale'],
  }),
  seed({
    id: 'fal-ai/seedvr/upscale/image',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'SeedVR2 Bild-Upscale',
    vendor: 'ByteDance',
    description: 'Bild-Upscaling mit Detailrekonstruktion.',
    capabilities: { imageInput: true, seed: true },
    tags: ['upscale'],
  }),
  seed({
    id: 'fal-ai/birefnet/v2',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'BiRefNet v2 (Freistellen)',
    vendor: 'BiRefNet',
    description: 'Hintergrundentfernung/Matting für Bilder, optional nur Maske. Ca. $0.0008 je Rechensekunde.',
    price: { unitPrice: 0.0008, unit: 'compute seconds', currency: 'USD' },
    capabilities: { imageInput: true },
    tags: ['matting'],
  }),
  seed({
    id: 'fal-ai/birefnet/v2/video',
    modality: 'tools',
    category: 'video-to-video',
    displayName: 'BiRefNet v2 Video (Freistellen)',
    vendor: 'BiRefNet',
    description: 'Hintergrundentfernung für Videos (Masken/Alpha).',
    capabilities: { videoInput: true },
    tags: ['matting'],
  }),
  seed({
    id: 'fal-ai/sam-3/image',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'SAM 3 (Segmentierung, Bild)',
    vendor: 'Meta',
    description: 'Segmentierung per Text-, Punkt- oder Box-Prompt; liefert Masken. $0.005 je Aufruf.',
    price: { unitPrice: 0.005, unit: 'requests', currency: 'USD' },
    capabilities: { imageInput: true },
    tags: ['segmentierung'],
  }),
  seed({
    id: 'fal-ai/sam-3/video',
    modality: 'tools',
    category: 'video-to-video',
    displayName: 'SAM 3 (Segmentierung, Video)',
    vendor: 'Meta',
    description: 'Objekt-Masken über die Zeit (Rotoscope-Grundlage).',
    capabilities: { videoInput: true },
    tags: ['segmentierung', 'rotoscope'],
  }),
  seed({
    id: 'fal-ai/image-preprocessors/depth-anything/v2',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'Depth Anything v2 (Tiefe)',
    vendor: 'fal',
    description: 'Tiefenkarte aus einem Bild.',
    capabilities: { imageInput: true },
    tags: ['tiefe'],
  }),
  seed({
    id: 'fal-ai/depth-anything-video',
    modality: 'tools',
    category: 'video-to-video',
    displayName: 'Depth Anything (Video)',
    vendor: 'fal',
    description: 'Tiefenkarten für Videos (Rotoscope, Parallaxe).',
    capabilities: { videoInput: true },
    tags: ['tiefe', 'rotoscope'],
  }),
  seed({
    id: 'fal-ai/dwpose',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'DWPose (Pose)',
    vendor: 'fal',
    description: 'Posen-/Skeletterkennung aus Bildern. Ca. $0.0006 je Rechensekunde.',
    price: { unitPrice: 0.0006, unit: 'compute seconds', currency: 'USD' },
    capabilities: { imageInput: true },
    tags: ['pose', 'rotoscope'],
  }),
  seed({
    id: 'fal-ai/rife/video',
    modality: 'tools',
    category: 'video-to-video',
    displayName: 'RIFE (Frame-Interpolation)',
    vendor: 'fal',
    description: 'Zwischenbilder für flüssigere Bewegung bzw. höhere fps. Ca. $0.0013 je Rechensekunde.',
    price: { unitPrice: 0.0013, unit: 'compute seconds', currency: 'USD' },
    capabilities: { videoInput: true },
    tags: ['interpolation'],
  }),
  seed({
    id: 'fal-ai/recraft/vectorize',
    modality: 'tools',
    category: 'image-to-image',
    displayName: 'Recraft Vectorize',
    vendor: 'Recraft',
    description: 'Wandelt Rastergrafiken in SVG-Vektoren um.',
    capabilities: { imageInput: true },
    tags: ['vektor'],
  }),
];

/** Kuratierte Felder je ID, die nach einem Sync erhalten bleiben. */
export function seedById(): Map<string, ModelInfo> {
  return new Map(SEED_MODELS.map((m) => [m.id, m]));
}
