import { CLAUDE_MODELS, type ModelInfo } from '@studio/core';

/**
 * Demo-Modellkatalog für den Browser-Modus. Die Einträge sind Beispieldaten (Namen, Preise, Fähigkeiten);
 * im echten Betrieb kommt der Katalog live aus der fal-Plattform-API.
 */
export const DEMO_MODELS: ModelInfo[] = [
  ...CLAUDE_MODELS,
  // Bild
  {
    id: 'fal-ai/nano-banana-pro',
    provider: 'fal',
    modality: 'image',
    displayName: 'Nano Banana Pro',
    vendor: 'Google',
    description: 'Bildgenerierung und -bearbeitung mit starker Typografie und Charakterkonsistenz über mehrere Referenzbilder.',
    price: { unitPrice: 0.04, unit: 'image', currency: 'USD' },
    capabilities: { imageInput: true, multiImageInput: true, aspectRatios: ['16:9', '9:16', '1:1', '4:5'], seed: true },
    recommended: true,
  },
  {
    id: 'fal-ai/flux-2/pro',
    provider: 'fal',
    modality: 'image',
    displayName: 'FLUX.2 Pro',
    vendor: 'Black Forest Labs',
    description: 'Fotorealistische Bilder mit präziser Prompt-Treue; schnell und günstig für Varianten.',
    price: { unitPrice: 0.03, unit: 'megapixel', currency: 'USD' },
    capabilities: { imageInput: true, seed: true, resolutions: ['1MP', '2MP', '4MP'] },
  },
  {
    id: 'fal-ai/seedream/v4.5',
    provider: 'fal',
    modality: 'image',
    displayName: 'Seedream 4.5',
    vendor: 'ByteDance',
    description: 'Hochauflösende Illustrationen und Poster-Layouts bis 4K, gute Textdarstellung.',
    price: { unitPrice: 0.03, unit: 'image', currency: 'USD' },
    capabilities: { imageInput: true, multiImageInput: true, resolutions: ['2K', '4K'] },
    status: 'beta',
  },
  // Video
  {
    id: 'minimax/h3-max/text-to-video',
    provider: 'fal',
    modality: 'video',
    alsoModalities: ['lipsync'],
    displayName: 'h3-max',
    vendor: 'MiniMax',
    description: 'Default-Videomodell: Text-, Bild- und Referenz-zu-Video, 5–15 s, 768p/1080p, native Tonspur und Audio-Eingang.',
    price: { unitPrice: 0.16, unit: 'second', currency: 'USD' },
    capabilities: {
      audioInput: true,
      imageInput: true,
      multiImageInput: true,
      nativeAudio: true,
      durations: [5, 10, 15],
      maxDurationSec: 15,
      aspectRatios: ['16:9', '9:16', '1:1'],
      resolutions: ['768p', '1080p'],
      seed: true,
    },
    recommended: true,
  },
  {
    id: 'fal-ai/kling-video/v3/pro',
    provider: 'fal',
    modality: 'video',
    displayName: 'Kling 3 Pro',
    vendor: 'Kuaishou',
    description: 'Filmische Kamerabewegungen und stabile Physik; Bild-zu-Video mit Start- und Endframe.',
    price: { unitPrice: 0.11, unit: 'second', currency: 'USD' },
    capabilities: { imageInput: true, durations: [5, 10], maxDurationSec: 10, aspectRatios: ['16:9', '9:16', '1:1'], resolutions: ['1080p'] },
  },
  {
    id: 'fal-ai/veo/v3-fast',
    provider: 'fal',
    modality: 'video',
    displayName: 'Veo 3 Fast',
    vendor: 'Google',
    description: 'Ältere Generation mit Ton; wird durch neuere Modelle ersetzt.',
    price: { unitPrice: 0.25, unit: 'second', currency: 'USD' },
    capabilities: { nativeAudio: true, durations: [8], maxDurationSec: 8, resolutions: ['720p', '1080p'] },
    status: 'deprecated',
  },
  // Lipsync
  {
    id: 'fal-ai/sync-lipsync/v3',
    provider: 'fal',
    modality: 'lipsync',
    displayName: 'Sync Lipsync 3',
    vendor: 'Sync Labs',
    description: 'Lippensynchronisation für bestehende Clips anhand einer Audiospur; erhält Mimik und Kopfbewegung.',
    price: { unitPrice: 0.05, unit: 'second', currency: 'USD' },
    capabilities: { audioInput: true, videoInput: true, maxDurationSec: 300 },
    recommended: true,
  },
  {
    id: 'fal-ai/omnihuman/v2',
    provider: 'fal',
    modality: 'lipsync',
    displayName: 'OmniHuman 2',
    vendor: 'ByteDance',
    description: 'Audiogetriebener Avatar aus einem Porträt: Gestik, Blick und Lippen passend zur Stimme.',
    price: { unitPrice: 0.14, unit: 'second', currency: 'USD' },
    capabilities: { audioInput: true, imageInput: true, maxDurationSec: 30 },
  },
  // Stimme
  {
    id: 'fal-ai/elevenlabs/tts/v3',
    provider: 'fal',
    modality: 'voice',
    displayName: 'ElevenLabs v3',
    vendor: 'ElevenLabs',
    description: 'Ausdrucksstarke Sprachausgabe in 70+ Sprachen mit Emotions-Tags; Stimmklon nur mit Einwilligung.',
    price: { unitPrice: 0.1, unit: '1k characters', currency: 'USD' },
    capabilities: { wordTimestamps: true },
    recommended: true,
  },
  {
    id: 'fal-ai/minimax/speech-2.6-hd',
    provider: 'fal',
    modality: 'voice',
    displayName: 'MiniMax Speech 2.6 HD',
    vendor: 'MiniMax',
    description: 'Natürliche Erzählerstimmen, Voice Design aus Beschreibung, gutes Deutsch.',
    price: { unitPrice: 0.06, unit: '1k characters', currency: 'USD' },
    capabilities: {},
  },
  // Musik
  {
    id: 'fal-ai/minimax-music/v2',
    provider: 'fal',
    modality: 'music',
    displayName: 'MiniMax Music 2',
    vendor: 'MiniMax',
    description: 'Songs mit Gesang und Lyrics bis 4 Minuten, Stil per Referenz-Track.',
    price: { unitPrice: 0.035, unit: 'request', currency: 'USD' },
    capabilities: { audioInput: true, maxDurationSec: 240 },
    recommended: true,
  },
  {
    id: 'fal-ai/stable-audio/v2',
    provider: 'fal',
    modality: 'music',
    displayName: 'Stable Audio 2',
    vendor: 'Stability AI',
    description: 'Instrumentale Musikbetten und Loops mit Tempo- und Tonartvorgabe.',
    price: { unitPrice: 0.02, unit: 'minute', currency: 'USD' },
    capabilities: { maxDurationSec: 180, seed: true },
  },
  // Sound
  {
    id: 'fal-ai/mmaudio-v2',
    provider: 'fal',
    modality: 'sound',
    displayName: 'MMAudio 2',
    vendor: 'MMAudio',
    description: 'Geräusche und Foley passend zum Video (Video-zu-Audio) oder aus Text.',
    price: { unitPrice: 0.001, unit: 'second', currency: 'USD' },
    capabilities: { videoInput: true, maxDurationSec: 30 },
    recommended: true,
  },
  {
    id: 'fal-ai/elevenlabs/sound-effects/v2',
    provider: 'fal',
    modality: 'sound',
    displayName: 'ElevenLabs SFX 2',
    vendor: 'ElevenLabs',
    description: 'Soundeffekte aus Textbeschreibung, 0,5–22 s, nahtlose Loops möglich.',
    price: { unitPrice: 0.002, unit: 'second', currency: 'USD' },
    capabilities: { maxDurationSec: 22 },
  },
  // Werkzeuge
  {
    id: 'fal-ai/whisper/v3-turbo',
    provider: 'fal',
    modality: 'tools',
    displayName: 'Whisper v3 Turbo',
    vendor: 'OpenAI',
    description: 'Transkription mit Wortzeitstempeln (Lyrics, Dialog, Diktat), sehr gutes Deutsch.',
    price: { unitPrice: 0.0012, unit: 'minute', currency: 'USD' },
    capabilities: { audioInput: true, wordTimestamps: true },
    recommended: true,
  },
  {
    id: 'fal-ai/demucs/v4',
    provider: 'fal',
    modality: 'tools',
    displayName: 'Demucs 4 (Stems)',
    vendor: 'Meta',
    description: 'Trennt Gesang, Drums, Bass und Rest – Grundlage für Lipsync und Mix.',
    price: { unitPrice: 0.02, unit: 'minute', currency: 'USD' },
    capabilities: { audioInput: true },
  },
  {
    id: 'fal-ai/topaz/upscale/video',
    provider: 'fal',
    modality: 'tools',
    displayName: 'Topaz Video Upscale',
    vendor: 'Topaz Labs',
    description: 'Hochskalieren auf 1080p/4K inkl. Bildraten-Interpolation.',
    price: { unitPrice: 0.08, unit: 'second', currency: 'USD' },
    capabilities: { videoInput: true, resolutions: ['1080p', '4K'] },
  },
  {
    id: 'fal-ai/sam-3/video',
    provider: 'fal',
    modality: 'tools',
    displayName: 'SAM 3 (Segmentierung)',
    vendor: 'Meta',
    description: 'Masken für Personen und Objekte über ganze Clips – Basis für Rotoscope-Overlays.',
    price: { unitPrice: 0.005, unit: 'compute second', currency: 'USD' },
    capabilities: { videoInput: true, imageInput: true },
  },
];
