import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react';
import type { ProjectCategory, Ref } from '@studio/core';
import { formatUsd, refLabel } from '@studio/core';
import { StudioProvider, useActions, useStudio, useStudioStore, useViewDocument } from '../../desktop/src/renderer/state/context.tsx';
import { createStudioStore, type StudioStore } from '../../desktop/src/renderer/state/store.ts';
import { useLanguage, useT } from '../../desktop/src/renderer/i18n.ts';
import { useWorkspaceLayout, LayoutProvider, type WorkspaceLayout } from '../../desktop/src/renderer/lib/layout.ts';
import { useContrastMode, useThemeMode } from '../../desktop/src/renderer/lib/theme.ts';
import { isEditableTarget } from '../../desktop/src/renderer/components/workspace/Workspace.tsx';
import { AssetBrowser } from '../../desktop/src/renderer/components/assets/AssetBrowser.tsx';
import { Monitor } from '../../desktop/src/renderer/components/monitor/Monitor.tsx';
import { Stage } from '../../desktop/src/renderer/components/stage/Stage.tsx';
import { NewProjectDialog } from '../../desktop/src/renderer/components/start/NewProjectDialog.tsx';
import { Toasts } from '../../desktop/src/renderer/components/common/Toasts.tsx';
import { Dialog } from '../../desktop/src/renderer/components/common/Dialog.tsx';
import { Icon, BrandMark, type IconName } from '../../desktop/src/renderer/components/common/Icon.tsx';
import { ThemeToggle } from '../../desktop/src/renderer/components/common/ThemeToggle.tsx';
import { QuestionCard, CheckpointCard, ApprovalCard } from '../../desktop/src/renderer/components/director/Cards.tsx';
import { JobTray } from '../../desktop/src/renderer/components/director/JobTray.tsx';
import { BudgetMeter } from '../../desktop/src/renderer/components/director/BudgetMeter.tsx';
import { ModelPickerPanel } from '../../desktop/src/renderer/components/picker/ModelPicker.tsx';
import { BrowserStudioApi } from './BrowserStudioApi.ts';
import { DirectorHostBridge, selectionText } from './hostBridge.ts';
import { SunoMusicDialog } from './SunoMusicDialog.tsx';

const categories: ProjectCategory[] = ['video', 'audio', 'slides', 'graphic', 'web'];
const icons: Record<ProjectCategory, IconName> = { video: 'film', audio: 'audio', slides: 'slides', graphic: 'layers', web: 'web' };
const exportTargets: Record<ProjectCategory, string[]> = { video: ['mp4','mov','wav','srt'], audio: ['wav','mp3','m4a','flac'], slides: ['pdf','pptx','png'], graphic: ['png','jpeg','pdf','svg'], web: ['zip'] };
function useWords() { const language = useLanguage(); return (de: string, en: string) => language === 'de' ? de : en; }

function NativeSettings({ onClose, api }: { onClose: () => void; api: BrowserStudioApi }) {
  const actions = useActions(); const word = useWords(); const settings = useStudio((s) => s.settings);
  const [theme, setTheme] = useThemeMode(); const [contrast, setContrast] = useContrastMode();
  const capabilities = useSyncExternalStore(api.host.subscribe,api.host.getStatus,api.host.getStatus);
  return <Dialog title={word('Einstellungen', 'Settings')} onClose={onClose} width={520}>
    <div className="form">
      <label className="field-label">{word('Sprache', 'Language')}<select className="field" value={settings?.language ?? 'de'} onChange={(e) => void actions.updateSettings({ language: e.target.value as 'de' | 'en' })}><option value="de">Deutsch</option><option value="en">English</option></select></label>
      <label className="field-label">{word('Darstellung', 'Appearance')}<select className="field" value={theme} onChange={(e) => setTheme(e.target.value as typeof theme)}><option value="dark">{word('Dunkel','Dark')}</option><option value="light">{word('Hell','Light')}</option><option value="system">System</option></select></label>
      <label className="field-label">{word('Kontrast','Contrast')}<select className="field" value={contrast} onChange={(e) => setContrast(e.target.value as typeof contrast)}><option value="system">System</option><option value="normal">Normal</option><option value="more">{word('Hoch','High')}</option></select></label>
      <p className="muted">{word('Director nutzt Modell, Unterhaltung und verfügbare Speicherfunktionen des nativen Hosts. Modell und Denkaufwand stellst du dort ein.','Director uses the native host model, conversation and available memory features. Choose the model and reasoning effort in the host.')}</p>
      <p className="muted">{word('Medienmodelle werden über das separat installierte Fal-Plugin mit deinem Fal-Konto ausgeführt. Projektmaterial, Fal Library und die native Dateibibliothek sind getrennte Speicher.','Media models run through the separately installed Fal plugin using your Fal account. Project assets, Fal Library and the native file library are separate stores.')}</p>
      <label><input type="checkbox" disabled={!capabilities.libraryExport} defaultChecked={api.saveExportsToLibrary} onChange={(e) => { api.saveExportsToLibrary = e.target.checked; }} /> {word('Exporte zusätzlich in der nativen Library speichern (falls verfügbar)','Save exports to the native library when available')}</label>
      {!capabilities.libraryExport && <p className="muted">{word('Dieser Host bietet keinen Library-Upload an. Exporte werden im Projekt gespeichert und als Download bereitgestellt.','This host does not expose library uploads. Exports are stored in the project and offered as downloads.')}</p>}
    </div>
  </Dialog>;
}

function NativeStart({ api }: { api: BrowserStudioApi }) {
  const actions = useActions(); const word = useWords(); const t = useT();
  const recent = useStudio((s) => s.recent); const [query, setQuery] = useState('');
  const [newCategory, setNewCategory] = useState<ProjectCategory | 'new' | null>(null); const [settings, setSettings] = useState(false);
  const projects = recent.filter((project) => project.title.toLowerCase().includes(query.toLowerCase()));
  return <div className="native-start">
    <header className="native-start-header"><BrandMark size={25}/><div><h1>AI Director Studio</h1><p>{word('Dein Material. Dein Film. Dein Director im nativen Chat.','Your material. Your film. Your director in the native chat.')}</p></div><span className="spacer"/><ThemeToggle/><button className="ibtn" aria-label={word('Einstellungen','Settings')} onClick={() => setSettings(true)}><Icon name="settings"/></button></header>
    <main className="native-start-main"><section className="native-create"><h2>{word('Was möchtest du gestalten?','What would you like to create?')}</h2><p className="muted">{word('Das Projekt bleibt gespeichert, während du mit ChatGPT oder Codex planst, Material auswählst und die nächsten Schritte freigibst.','The project stays saved while you plan with ChatGPT or Codex, choose material and approve the next steps.')}</p><button className="btn primary lg" onClick={() => setNewCategory('new')}><Icon name="plus"/> {word('Neues Projekt','New project')}</button><div className="native-categories">{categories.map((category) => <button key={category} className="native-category" onClick={() => setNewCategory(category)}><Icon name={icons[category]} size={24}/><strong>{t(`category.${category}`)}</strong><span>{t(`start.examples.${category}`)}</span></button>)}</div></section>
    <section className="native-recent"><div className="native-section-heading"><h2>{word('Deine Projekte','Your projects')}</h2><button className="ibtn" aria-label={word('Aktualisieren','Refresh')} onClick={() => void actions.loadRecent()}><Icon name="refresh"/></button></div><input type="search" className="field" placeholder={word('Projekt suchen…','Search projects…')} value={query} onChange={(e) => setQuery(e.target.value)}/>{projects.length ? <ul className="native-project-list">{projects.map((project) => <li key={project.path}><button onClick={() => void actions.openProject(project.path)}><Icon name={project.category ? icons[project.category] : 'folder'} size={25}/><span><strong>{project.title}</strong><small>{project.category ? t(`category.${project.category}`) : t('category.unset')} · {new Date(project.updatedAt).toLocaleDateString()} {project.checkpoint ? `· ${project.checkpoint.title}` : ''}</small></span><Icon name="chevronRight"/></button></li>)}</ul> : <p className="native-empty">{recent.length ? word('Keine passenden Projekte.','No matching projects.') : word('Lege dein erstes Projekt an.','Create your first project.')}</p>}</section></main>
    {newCategory && <NewProjectDialog {...(newCategory === 'new' ? {} : { initialCategory: newCategory })} onClose={() => setNewCategory(null)}/>} {settings && <NativeSettings api={api} onClose={() => setSettings(false)}/>}
  </div>;
}

function ReferenceContext({ host }: { host: DirectorHostBridge }) {
  const word = useWords(); const actions = useActions(); const status = useSyncExternalStore(host.subscribe, host.getStatus, host.getStatus);
  const projectId = useStudio((s) => s.projectId); const title = useStudio((s) => s.manifest?.title ?? ''); const document = useViewDocument();
  const assets = useStudio((s) => s.assets); const version = useStudio((s) => s.viewing?.number ?? s.documentVersion); const composer = useStudio((s) => s.composer);
  const refs = useMemo(() => composer.flatMap((segment) => segment.type === 'ref' ? [segment.ref] : []), [composer]);
  const context = useMemo(() => projectId ? { projectId, title, document, version, assets, refs } : null, [projectId, title, document, version, assets, refs]);
  const text = context ? selectionText(context) : '';
  const [synced, setSynced] = useState(false); const [copying, setCopying] = useState(false);
  useEffect(() => { let live = true; void host.updateSelection(context).then((ok) => { if (live) setSynced(ok); }).catch((error) => { if (live) { setSynced(false); actions.toast('error', String(error)); } }); return () => { live = false; }; }, [host, context, status.modelContext, status.contextAttached, actions]);
  const copy = async () => { await navigator.clipboard.writeText(text); setCopying(true); setTimeout(() => setCopying(false), 1800); };
  return <section className="native-context" aria-label={word('Auswahl für den Director','Selection for the director')}><div className="native-context-head"><Icon name="cursor" size={14}/><strong>{word('Auswahl','Selection')}</strong><span className="native-context-status" role="status">{synced ? word('Kontext für deinen nächsten Chatturn','Context for your next chat turn') : word('Kontext kopieren und im Chat einfügen','Copy context and paste it into chat')}</span><button className="btn sm" onClick={() => void copy().catch((error) => actions.toast('error', String(error)))}>{copying ? word('Kopiert','Copied') : word('Kopieren','Copy')}</button>{refs.length > 0 && <button className="ibtn sm" aria-label={word('Auswahl löschen','Clear selection')} onClick={() => actions.setComposer([])}><Icon name="close" size={12}/></button>}</div>{refs.length > 0 && <div className="native-ref-chips">{refs.map((ref, index) => <button className="native-ref-chip" key={index} onClick={() => actions.revealRef(ref)}>{refLabel(ref, { fps: document?.kind === 'timeline' ? document.fps : 30 })}</button>)}</div>}<span className="sr-only">{word('Auswahl sendet keine Nachricht.','Selection does not send a message.')}</span></section>;
}

function NativeJobs({ api }: {api:BrowserStudioApi}) {
  const jobs = useSyncExternalStore(api.subscribeJobs,api.getJobs,api.getJobs); const projectId = useStudio((s) => s.projectId); const actions = useActions(); const word=useWords();
  if(!jobs.length) return null;
  return <details className="native-jobs"><summary>{word('Medienjobs','Media jobs')} <span className="mono">{jobs.length}</span></summary><p className="muted">{word('Browserverarbeitung läuft während der Editor geöffnet ist. Unterbrochene Jobs können hier fortgesetzt werden. Fal-Aufträge laufen beim Anbieter weiter.','Browser processing runs while the editor is open. Interrupted jobs can be resumed here. Fal jobs continue at the provider.')}</p>{[...jobs].reverse().map((job) => <div className="native-job-row" key={job.id}><span><strong>{job.kind}</strong> · {job.status}{job.error && <small>{job.error}</small>}</span>{(job.status === 'running' || job.status === 'queued') && <button className="btn sm" onClick={() => void api.cancelMediaJob(projectId!,job.id).catch((error) => actions.toast('error',String(error)))}>{word('Abbrechen','Cancel')}</button>}{(job.status === 'failed'||job.status === 'canceled') && <button className="btn sm" onClick={() => void api.retryMediaJob(projectId!,job.id).catch((error) => actions.toast('error',String(error)))}>{word('Erneut versuchen','Retry')}</button>}{job.status === 'running' && job.executorId !== api.executorId && <button className="btn sm" onClick={() => void api.resumeMediaJob(projectId!,job.id).catch((error) => actions.toast('error',String(error)))}>{word('Fortsetzen','Resume')}</button>}</div>)}</details>;
}

function NativeWorkspace({ api, host }: { api: BrowserStudioApi; host: DirectorHostBridge }) {
  const word = useWords(); const t = useT(); const actions = useActions(); const store = useStudioStore(); const document = useViewDocument();
  const manifest = useStudio((s) => s.manifest); const budget = useStudio((s) => s.budget); const versions = useStudio((s) => s.versions); const viewing = useStudio((s) => s.viewing); const head = useStudio((s) => s.documentVersion);
  const question = useStudio((s) => s.question); const approvals = useStudio((s) => s.approvals); const checkpoints = useStudio((s) => s.checkpoints); const assets = useStudio((s) => s.assets);
  const mediaJobs = useSyncExternalStore(api.subscribeJobs,api.getJobs,api.getJobs);
  const cancelExport = mediaJobs.find((job)=>job.id===api.exportJobId && (job.status==='queued'||job.status==='running'));
  const baseLayout = useWorkspaceLayout({ category: manifest?.category ?? null, doc: document });
  const [assetsOpen, setAssetsOpen] = useState(window.innerWidth >= 900); const [dialog, setDialog] = useState<'settings'|'versions'|'export'|'decisions'|'models'|'budget'|'import-url'|'suno'|null>(null);
  const [exporting, setExporting] = useState(false); const [progress, setProgress] = useState<{phase:string;progress:number}|null>(null); const [importUrl, setImportUrl] = useState('');
  const nativeStatus = useSyncExternalStore(host.subscribe, host.getStatus, host.getStatus);
  const decisionCount = approvals.length + checkpoints.filter((checkpoint) => checkpoint.status === 'proposed').length + (question ? 1 : 0);
  const narrow = window.innerWidth < 760;
  const layout: WorkspaceLayout = { ...baseLayout, sideL: assetsOpen && !narrow ? 260 : 0, sideR: 0, indexW: narrow ? 112 : 168, collapsed: { ...baseLayout.collapsed, assets: !assetsOpen, director: true }, toggle: (panel) => panel === 'assets' ? setAssetsOpen((value) => !value) : baseLayout.toggle(panel), setCollapsed: (panel, collapsed) => panel === 'assets' ? setAssetsOpen(!collapsed) : baseLayout.setCollapsed(panel, collapsed) };
  useEffect(() => { api.onExportProgress = (phase, progress) => setProgress({phase,progress}); return () => { api.onExportProgress = undefined; }; }, [api]);
  useEffect(() => { const handle = (event: KeyboardEvent) => { if (event.defaultPrevented || isEditableTarget(event.target)) return; const state = store.getState(); const mod = event.metaKey || event.ctrlKey; if (mod && event.key === '1') { event.preventDefault(); setAssetsOpen((v) => !v); return; } if (event.ctrlKey || event.metaKey || event.altKey || state.document?.kind !== 'timeline') return; if (event.key === ' ' && !(event.target as HTMLElement).closest('button,a')) { event.preventDefault(); actions.togglePlay(); } if ('jkl'.includes(event.key.toLowerCase())) actions.shuttle(event.key.toLowerCase() as 'j'|'k'|'l'); if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { event.preventDefault(); state.transport?.pause(); actions.requestSeek(state.playhead + (event.key === 'ArrowLeft' ? -1 : 1)); } }; window.addEventListener('keydown', handle); return () => window.removeEventListener('keydown', handle); }, [actions, store]);
  async function runExport(target: string) { if (!manifest || exporting) return; setExporting(true); setProgress({phase:word('Export vorbereiten','Preparing export'),progress:0}); try { const result = await api.exportProject(manifest.id, {target, ...(store.getState().formatId ? {format:store.getState().formatId!} : {})}); actions.toast('success',result.path); setDialog(null); } catch(error) { actions.toast('error',error instanceof Error ? error.message : String(error)); } finally { setExporting(false); setProgress(null); } }
  return <LayoutProvider value={layout}><div className={`native-workspace${assetsOpen ? ' has-assets' : ''}`} style={{'--side-l':`${layout.sideL}px`,'--side-r':'0px','--stage-h':`${Math.max(220,baseLayout.stageH)}px`,'--index-w':`${layout.indexW}px`} as React.CSSProperties}>
    <header className="native-header"><button className="ibtn" aria-label={word('Projekte','Projects')} onClick={() => actions.closeProject()}><Icon name="chevronLeft"/></button><BrandMark size={18}/><h1 title={manifest?.title}>{manifest?.title}</h1><span className="badge native-category-badge">{manifest?.category ? t(`category.${manifest.category}`) : word('Planung','Planning')}</span><span className="spacer"/><button className="btn sm" onClick={() => setDialog('versions')}>v{viewing?.number ?? head}</button>{budget && <button className="btn sm native-budget" onClick={() => setDialog('budget')}>{formatUsd(budget.spentUsd)} / {formatUsd(budget.approvedUsd)}</button>}<button className="btn sm" onClick={() => setDialog('export')} disabled={!document}><Icon name="export" size={14}/><span className="native-label">{word('Exportieren','Export')}</span></button><button className="ibtn" aria-label={word('Einstellungen','Settings')} onClick={() => setDialog('settings')}><Icon name="settings"/></button></header>
    <nav className="native-toolbar" aria-label={word('Projektwerkzeuge','Project tools')}><button className="btn sm" aria-pressed={assetsOpen} onClick={() => setAssetsOpen((v) => !v)}><Icon name="sideLeft" size={14}/>{word('Material','Material')} <span className="mono">{assets.filter((asset)=>!(asset.source==='derived' && asset.subtype==='thumbnail' && asset.metadata?.sourceAssetId)).length}</span></button><button className="btn sm" onClick={() => void actions.importFiles('import')}><Icon name="plus" size={14}/>{word('Importieren','Import')}</button>{nativeStatus.libraryImport && <button className="btn sm" onClick={() => void api.importLibraryFiles(manifest!.id).then(() => actions.refreshSnapshot()).catch((error) => actions.toast('error',String(error)))}>{word('Dateibibliothek','File library')}</button>}<button className="btn sm" onClick={() => setDialog('import-url')}><Icon name="link" size={14}/>URL</button><button className="btn sm" onClick={() => setDialog('models')}>{word('Medienmodelle','Media models')}</button><button className="btn sm" onClick={() => setDialog('suno')}>Suno</button><span className="spacer"/>{decisionCount > 0 && <button className="btn primary sm" onClick={() => setDialog('decisions')}>{word('Prüfen','Review')} <span className="mono">{decisionCount}</span></button>}</nav>
    {assetsOpen && <div className="native-assets-wrap"><AssetBrowser/>{narrow && <button className="btn native-assets-close" onClick={() => setAssetsOpen(false)}>{word('Material schließen','Close material')}</button>}</div>}
    <div className="native-monitor-wrap"><Monitor/>{api.missingAssets.size > 0 && <div className="native-repair-banner" role="alert">{word('Fehlendes Material: bitte in der Materialansicht neu zuordnen.','Missing material: relink it in the material panel.')} {Array.from(api.missingAssets.keys()).join(', ')}</div>}{!document && <div className="native-planning-note">{word('Beschreibe dein Vorhaben im nativen Chat. Der Director kann Brief, Kategorie und Checkpoints im Projekt speichern.','Describe your project in the native chat. The director can save the brief, category and checkpoints in the project.')}</div>}</div>
    <div className="native-selection-wrap"><NativeJobs api={api}/><JobTray/><ReferenceContext host={host}/></div><div className="native-stage-wrap"><Stage/></div>
    {dialog === 'settings' && <NativeSettings api={api} onClose={() => setDialog(null)}/>}
    {dialog === 'suno' && <SunoMusicDialog api={api} onClose={() => setDialog(null)}/>}
    {dialog === 'models' && <Dialog title={word('Medienmodelle','Media models')} onClose={() => setDialog(null)} width={660}><p className="muted">{word('Auswahl und Freigaben gelten für Fal-Aufträge, die dein nativer Host über das offizielle Fal-Plugin ausführt.','Selections and approvals apply to Fal jobs executed by your native host through the official Fal plugin.')}</p><ModelPickerPanel autoFocus/></Dialog>}
    {dialog === 'budget' && budget && <Dialog title={word('Projektbudget','Project budget')} onClose={() => setDialog(null)}><BudgetMeter budget={budget} detailed/></Dialog>}
    {dialog === 'decisions' && <Dialog title={word('Fragen und Freigaben','Questions and approvals')} onClose={() => setDialog(null)} width={620}><div className="native-decisions">{question && <QuestionCard question={question}/>} {approvals.map((request) => <ApprovalCard request={request} key={request.id}/>)} {checkpoints.filter((checkpoint) => checkpoint.status === 'proposed').map((checkpoint) => <CheckpointCard checkpoint={checkpoint} key={checkpoint.id}/>)}{!decisionCount && <p>{word('Alle Entscheidungen sind gespeichert.','All decisions have been saved.')}</p>}</div></Dialog>}
    {dialog === 'versions' && <Dialog title={word('Projektversionen','Project versions')} onClose={() => setDialog(null)} width={600}><ul className="native-version-list">{[...versions].reverse().map((version) => <li key={version.number}><span><strong>v{version.number}</strong> · {version.note}<small>{new Date(version.createdAt).toLocaleString()}</small></span><button className="btn sm" onClick={() => { void actions.viewVersion(version.number); setDialog(null); }}>{word('Ansehen','View')}</button>{version.number !== head && <button className="btn sm" onClick={() => { void actions.restoreVersion(version.number); setDialog(null); }}>{word('Wiederherstellen','Restore')}</button>}</li>)}</ul>{viewing && <button className="btn" onClick={() => { actions.exitVersionView(); setDialog(null); }}>{word('Zur aktuellen Version','Back to current version')}</button>}</Dialog>}
    {dialog === 'export' && <Dialog title={word('Projekt exportieren','Export project')} onClose={() => { if (!exporting) setDialog(null); }} width={540}><p className="muted">{word('Der Export wird im Projekt gespeichert und heruntergeladen. Fehlendes Material muss vorher repariert werden.','The export is saved to the project and downloaded. Missing media must be repaired first.')}</p><div className="native-export-targets">{(manifest?.category ? exportTargets[manifest.category] : []).map((target) => <button className="btn" key={target} disabled={exporting} onClick={() => void runExport(target)}>{target.toUpperCase()}</button>)}</div>{progress && <div role="status"><p>{progress.phase} · {Math.round(progress.progress * 100)}%</p><progress max="1" value={progress.progress}/>{cancelExport && <button className="btn" onClick={()=>void api.cancelMediaJob(manifest!.id,cancelExport.id).catch((error)=>actions.toast('error',String(error)))}>{word('Export abbrechen','Cancel export')}</button>}</div>}</Dialog>}
    {dialog === 'import-url' && <Dialog title={word('Material aus URL importieren','Import material from URL')} onClose={() => setDialog(null)} footer={<button className="btn primary" disabled={!importUrl.trim()} onClick={() => void api.action(manifest!.id,'importUrl',{url:importUrl.trim()}).then(() => { setDialog(null); void actions.refreshSnapshot(); }).catch((error) => actions.toast('error',String(error)))}>{word('Importieren','Import')}</button>}><label className="field-label">URL<input type="url" className="field" value={importUrl} onChange={(e) => setImportUrl(e.target.value)} data-autofocus/></label><p className="muted">{word('Für ein Fal-Ergebnis übergibt der Host zusätzlich Auftrag, Modell und Kostennachweis an Director. Ein URL-Import allein belegt keine Fal-Herkunft.','For a Fal result the host also hands the request, model and cost receipt to Director. URL import alone does not establish Fal provenance.')}</p></Dialog>}
  </div></LayoutProvider>;
}

function NativeScreens({ api, host }: { api: BrowserStudioApi; host: DirectorHostBridge }) {
  const store = useStudioStore(); const screen = useStudio((s) => s.screen); const hostStatus = useSyncExternalStore(host.subscribe,host.getStatus,host.getStatus);
  const [loading,setLoading] = useState(true); const word = useWords();
  useEffect(() => { let live = true; void host.connect().then(() => store.getState().init()).then(() => { if(live) setLoading(false); }); return () => {live=false;}; },[host,store]);
  useEffect(() => host.onLaunch((data) => { const projectId = typeof data.projectId === 'string' ? data.projectId : (data.snapshot as {manifest?:{id?:string}})?.manifest?.id; if(projectId) void store.getState().openProject(projectId); }),[host,store]);
  if(loading) return <div className="native-loading" role="status"><BrandMark size={35}/><span>{word('Director Studio wird verbunden…','Connecting Director Studio…')}</span></div>;
  return <>{hostStatus.error && <div className="native-host-error" role="alert">{word('Hostverbindung','Host connection')}: {hostStatus.error}</div>}{screen === 'start' ? <NativeStart api={api}/> : <NativeWorkspace api={api} host={host}/>}<Toasts/></>;
}
export function NativeEditor({ api, host, store }: { api: BrowserStudioApi; host: DirectorHostBridge; store?: StudioStore }) {
  const studioStore = useMemo(() => store ?? createStudioStore(api),[api,store]);
  return <StudioProvider api={api} store={studioStore}><NativeScreens api={api} host={host}/></StudioProvider>;
}
