import { build } from 'esbuild';
import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { unzipSync } from 'fflate';
import { PDFDocument } from 'pdf-lib';
const run = promisify(execFile), studio = fileURLToPath(new URL('../../../', import.meta.url)), dist = path.resolve(studio, '../dist/client');
const output = await fs.mkdtemp(path.join(os.tmpdir(), 'director-browser-outputs.'));
const fixture = process.env.DIRECTOR_VIDEO_FIXTURE ?? '/tmp/director-fal-import.2iLmVd/FAL Import Smoke.dstudio/assets/store/e2/00/e200e4fb63b15927104a8103e32379702a537e0b22ddc4f372145a52a5a16399.mp4';
const worker = (await import(path.resolve(studio,'../dist/server/index.js'))).default;
await build({ stdin: { contents: "import * as media from './packages/browser-media/src/index.ts';import * as core from './packages/core/src/index.ts';window.media=media;window.core=core;", resolveDir: studio, sourcefile: 'browser-smoke.ts' }, outfile: path.join(output, 'test.js'), bundle: true, platform: 'browser', format: 'esm', target: 'chrome140', define: { 'process.env.NODE_ENV': '"production"' } });
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.wasm': 'application/wasm', '.woff2': 'font/woff2', '.mp4': 'video/mp4', '.svg': 'image/svg+xml' };
const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost'); res.setHeader('access-control-allow-origin', '*'); res.setHeader('cross-origin-resource-policy', 'cross-origin');
  try {
    if (url.pathname === '/') { res.setHeader('content-type', 'text/html'); res.end('<!doctype html><html><body><script type="module" src="/test.js"></script></body></html>'); return; }
    const corruptRoute=/^\/runtime\/ffmpeg\/(test-corrupt-part|test-bad-checksum)\/(ffmpeg-core\.wasm\.json|ffmpeg-core\.wasm\.part\d+)$/.exec(url.pathname);
    if(corruptRoute){let bytes=await fs.readFile(path.join(dist,'runtime/ffmpeg',corruptRoute[2]));if(corruptRoute[2].endsWith('.json')&&corruptRoute[1]==='test-bad-checksum'){const manifest=JSON.parse(bytes);manifest.sha256='0'.repeat(64);bytes=Buffer.from(JSON.stringify(manifest));}else if(corruptRoute[2].endsWith('.part0')&&corruptRoute[1]==='test-corrupt-part'){bytes=Buffer.from(bytes);bytes[0]^=1;}const response=await worker.fetch(new Request(`http://127.0.0.1:${server.address().port}${url.pathname}`),{ASSETS:{fetch:async()=>new Response(bytes,{headers:{'content-type':corruptRoute[2].endsWith('.json')?'application/json':'application/octet-stream'}})}});for(const[name,value]of response.headers)res.setHeader(name,value);res.writeHead(response.status);res.end(Buffer.from(await response.arrayBuffer()));return;}
    const filename = url.pathname === '/test.js' ? path.join(output, 'test.js') : url.pathname === '/fixture.mp4' ? fixture : url.pathname.startsWith('/reopened/') ? path.resolve(output, '.' + url.pathname) : path.resolve(dist, `.${url.pathname}`);
    if (filename !== fixture && !filename.startsWith(dist + path.sep) && !filename.startsWith(path.join(output,'reopened') + path.sep) && filename !== path.join(output, 'test.js')) { res.writeHead(403); res.end(); return; }
    const bytes = await fs.readFile(filename), type = mime[path.extname(filename)] ?? 'application/octet-stream';
    if (filename.startsWith(dist + path.sep)) { const response = await worker.fetch(new Request(`http://127.0.0.1:${server.address().port}${url.pathname}`), { ASSETS: { fetch: async () => new Response(bytes, {headers:{'content-type':type}}) } }); for(const[name,value]of response.headers)res.setHeader(name,value); res.writeHead(response.status); res.end(Buffer.from(await response.arrayBuffer())); }
    else { res.setHeader('content-type', type); res.end(bytes); }
  } catch (error) { res.writeHead(404); res.end(String(error)); }
});
await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve)); const port = server.address().port;
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; page.on('pageerror', (error) => errors.push(error.message));
page.on('console',(msg)=>{if(msg.text().startsWith('sandbox-stage')||msg.type()==='error'&&/Content Security|Refused|blocked|Failed/.test(msg.text()))console.log(msg.text().slice(0,1000));});
await page.exposeBinding('saveOutput', async (_, filename, base64, metadata) => { await fs.writeFile(path.join(output, filename), Buffer.from(base64, 'base64')); report.formats.push(metadata); });
const report = { output, fixture, formats: [], checks: {}, browserErrors: errors };
try {
  await page.goto(`http://127.0.0.1:${port}/`); await page.waitForFunction(() => window.media && window.core);
  const result = await page.evaluate(async () => {
    const m = window.media, c = window.core, formats = [], checks = {};
    const save = async (result) => { const bytes = new Uint8Array(await result.blob.arrayBuffer()); let raw = ''; for (let i=0;i<bytes.length;i+=32768) raw += String.fromCharCode(...bytes.subarray(i,i+32768)); const metadata={filename:result.filename,mime:result.mimeType,bytes:bytes.length,warnings:result.warnings};await window.saveOutput(result.filename,btoa(raw),metadata);formats.push(metadata); };
    for(const [path,expected,key]of[['test-corrupt-part','WASM-Teilstück ffmpeg-core.wasm.part0: SHA-256','runtimeCorruptPartRejected'],['test-bad-checksum','WASM-Laufzeit: SHA-256','runtimeBadWholeHashRejected']]){let error='';try{await m.loadWasmRuntime(new URL(`/runtime/ffmpeg/${path}/ffmpeg-core.wasm.json`,document.baseURI));}catch(cause){error=String(cause);}if(!error.includes(expected))throw new Error(`Runtime integrity did not reject ${path}: ${error}`);checks[key]={rejected:true,error};}
    const canvas = c.createCanvas({width:320,height:180,background:'#15304e'}); canvas.layers.push({id:'text',type:'text',x:20,y:50,width:280,height:100,text:'Director Studio Test',style:{fontSize:28,color:'#f4bc60'}});
    for (const format of ['png','jpeg','svg','pdf']) await save(await m.exportProject({document:canvas,assets:{},format,filename:`canvas.${format}`}));
    const deck = c.createDeck({width:640,height:360});deck.theme.fonts={heading:'Instrument Sans',body:'Instrument Sans',mono:'IBM Plex Mono'};deck.theme.fontAssets={'Instrument Sans':'font'};const deckAssets={font:{id:'font',kind:'font',url:'/fonts/InstrumentSans-Variable.woff2'},photo:{id:'photo',kind:'image',url:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50"><rect width="100" height="50" fill="#f4bc60"/></svg>')}}; deck.slides.push({id:'s1',background:'#152b41',notes:'Speaker note preserved',elements:[{id:'title',type:'text',x:30,y:40,width:580,height:120,text:'Real browser **export**',style:{color:'#ffffff',fontSize:48,fontWeight:'bold',textAlign:'center',background:'rgba(20,120,220,0.25)'}},{id:'chart',type:'chart',x:40,y:180,width:300,height:150,chart:{type:'bar',labels:['A','B'],series:[{name:'Demo',values:[3,5]}]}}]},{id:'s2',elements:[{id:'shape',type:'shape',shape:'ellipse',x:100,y:70,width:180,height:180,style:{fill:'rgba(244,188,96,.5)',radius:16}},{id:'bullets',type:'text',x:20,y:15,width:200,height:70,text:'- Editable **bold**\n- *italic*',style:{fontSize:24}},{id:'picture',type:'image',assetId:'photo',x:320,y:80,width:120,height:140,style:{objectFit:'contain'}}]});
    for (const format of ['png','pdf','pptx']) await save(await m.exportProject({document:deck,assets:deckAssets,format,filename:`deck.${format}`}));
    const rate=48000, music=Float32Array.from({length:rate*2},(_,i)=>Math.sin(i/rate*2*Math.PI*330)*.16), voice=Float32Array.from({length:rate},(_,i)=>i<rate*.6?Math.sin(i/rate*2*Math.PI*440)*.2:0);
    const musicBlob=m.encodeWav([music,music],rate),voiceBlob=m.encodeWav([voice,voice],rate), assets={video:{id:'video',kind:'video',url:'/fixture.mp4'},music:{id:'music',kind:'audio',url:URL.createObjectURL(musicBlob)},voice:{id:'voice',kind:'audio',url:URL.createObjectURL(voiceBlob)}};
    const timeline=c.createTimeline({fps:30,format:{id:'smoke',width:320,height:180},durationFrames:60}); timeline.tracks[0].clips.push({id:'v1',assetId:'video',start:0,duration:60,in:6,speed:1.25,gainDb:-4,fadeInFrames:6,fadeOutFrames:6,includeSourceAudio:true});timeline.tracks[3].clips.push({id:'speech',assetId:'voice',start:15,duration:30,in:0,speed:1,gainDb:-3,fadeInFrames:3,fadeOutFrames:3});timeline.tracks[4].duck={byTrackId:'A1',db:-12,mode:'signal'};timeline.tracks[4].clips.push({id:'music',assetId:'music',start:0,duration:60,in:0,speed:1});
    const probe=await m.probeMedia(await (await fetch('/fixture.mp4')).blob());checks.probe=probe;
    const sheet=await m.contactSheet(await (await fetch('/fixture.mp4')).blob(),{count:4,columns:2,tileWidth:160});await save({blob:sheet,filename:'contact-sheet.png',mimeType:sheet.type,warnings:[]});
    const audio=m.analyzeAudio(voiceBlob);const analyzed=await audio;checks.audioAnalysis={durationMs:analyzed.durationMs,sampleRate:analyzed.sampleRate,channels:analyzed.channels,rmsDb:analyzed.rmsDb,loudness:analyzed.loudness,peaks:analyzed.peaks.length};
    for(const format of ['wav','mp3','m4a','flac','mp4','mov','png']) await save(await m.exportProject({document:timeline,assets,format,filename:`timeline.${format}`,options:{normalizeLufs:-16}}));
    const audioOnly=structuredClone(timeline);audioOnly.tracks[0].clips[0].includeSourceAudio=false;const premix=await m.mixTimelineAudio(audioOnly,assets,{normalizeLufs:-16});checks.normalizedLoudness=await m.measureLoudness(premix,-16);
    const decoded=await m.decodeAudio(premix),pcm=decoded.getChannelData(0);const magnitude=(from,to,freq)=>{let re=0,im=0;for(let i=Math.floor(from*decoded.sampleRate);i<Math.floor(to*decoded.sampleRate);i++){re+=pcm[i]*Math.cos(i/decoded.sampleRate*Math.PI*2*freq);im+=pcm[i]*Math.sin(i/decoded.sampleRate*Math.PI*2*freq);}return Math.hypot(re,im)/(Math.floor((to-from)*decoded.sampleRate));};const initial=magnitude(.15,.35,330),ducked=magnitude(.8,1,330),released=magnitude(1.8,1.95,330);checks.signalDuck={initial,ducked,released,duckDb:20*Math.log10(ducked/initial),recovers:released>ducked*1.5};
    const source="import React from 'react';export default function Overlay(p){let isolated=false;try{void window.parent.document;}catch{isolated=true;}return <div style={{position:'absolute',left:12,top:14,color:'#ffd377',fontSize:26,background:'#001a35'}}>{isolated?'Isolated TSX':'UNSAFE'} {p.frame} {p.words[0]?.text}</div>}";
    const generated=structuredClone(timeline);generated.components.demo={assetId:'source',name:'Overlay'};generated.tracks[1].clips.push({id:'overlay',componentId:'demo',start:0,duration:60,in:0,speed:1});const codeAsset={id:'source',kind:'code',url:URL.createObjectURL(new Blob([source],{type:'text/plain'}))};
    await save(await m.exportProject({document:generated,assets:{...assets,source:codeAsset},components:{demo:source},words:[{text:'Word',start:0,end:1}],format:'png',filename:'sandbox-component.png',options:{frame:12},onProgress:(phase,progress)=>console.log('sandbox-stage',phase,progress)}));
    const componentAudio=await m.exportProject({document:generated,assets:{...assets,source:codeAsset},components:{demo:source},format:'wav',filename:'component-audio.wav'});await save(componentAudio);checks.defaultAudioLoudness=await m.measureLoudness(componentAudio.blob,-14);
    await save(await m.exportProject({document:generated,assets:{...assets,source:codeAsset},components:{demo:source},format:'mp4',filename:'component-video.mp4'}));
    const previewFrame=document.createElement('iframe');previewFrame.sandbox.add('allow-scripts');previewFrame.style.cssText='width:320px;height:180px';const client=new m.MediaSandboxClient(previewFrame);previewFrame.src='/media-sandbox.html';document.body.append(previewFrame);
    await client.preview({document:generated,assets:{...assets,source:codeAsset},components:{demo:source},words:[{text:'Word',start:0,end:1}],format:'mp4'});client.seekTo(10);client.play();await new Promise(r=>setTimeout(r,400));client.pause();await new Promise(r=>setTimeout(r,100));checks.sandboxPreview={frame:client.getCurrentFrame(),isPlaying:client.isPlaying()};client.dispose();previewFrame.remove();
    const silentVideo=await m.withFFmpeg(async ff=>{await ff.writeFile('in.mp4',new Uint8Array(await(await fetch('/fixture.mp4')).arrayBuffer()));if(await ff.exec(['-i','in.mp4','-an','-c:v','copy','out.mp4']))throw Error('silent fixture');return new Blob([new Uint8Array(await ff.readFile('out.mp4'))],{type:'video/mp4'});});
    const silentTimeline=c.createTimeline({fps:30,durationFrames:30});silentTimeline.tracks[0].clips.push({id:'silent',assetId:'silent',start:0,duration:30,in:0,speed:1,includeSourceAudio:true});const silentMix=await m.mixTimelineAudio(silentTimeline,{silent:{id:'silent',kind:'video',url:URL.createObjectURL(silentVideo)}});const silentDecoded=await m.decodeAudio(silentMix);checks.silentVideoAudio=Math.max(...silentDecoded.getChannelData(0))===0;
    const masked=c.createCanvas({width:100,height:100,background:'#e0d0c0'});masked.layers.push({id:'masked',type:'image',assetId:'paint',maskAssetId:'mask',blend:'multiply',x:0,y:0,width:100,height:100});const svgUrl=svg=>'data:image/svg+xml,'+encodeURIComponent(svg);const maskAssets={paint:{id:'paint',kind:'image',url:svgUrl('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#0044ff"/></svg>')},mask:{id:'mask',kind:'image',url:svgUrl('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="black"/><rect width="50" height="100" fill="white"/></svg>')}};const maskedOut=await m.exportProject({document:masked,assets:maskAssets,format:'png',filename:'masked-canvas.png'});await save(maskedOut);const bmp=await createImageBitmap(maskedOut.blob),pixelCanvas=document.createElement('canvas');pixelCanvas.width=100;pixelCanvas.height=100;const pixelCtx=pixelCanvas.getContext('2d');pixelCtx.drawImage(bmp,0,0);bmp.close();checks.canvasMaskBlend={masked:[...pixelCtx.getImageData(20,50,1,1).data],background:[...pixelCtx.getImageData(80,50,1,1).data]};
    const htmlFiles={'index.html':'<!doctype html><html><head><link rel="stylesheet" href="style.css"></head><body><h1 id="heading">Director static website</h1><img id="local-image" src="images/logo.svg"><a href="about/index.html">About</a><script src="scripts/main.js"></script></body></html>','about/index.html':'<!doctype html><html><head><link rel="stylesheet" href="../style.css"></head><body><h1>About local page</h1><img src="../images/logo.svg"></body></html>','style.css':'@import "colors.css";h1{font-family:Demo;background-image:url(images/logo.svg)}@font-face{font-family:Demo;src:url(fonts/demo.woff2)}','colors.css':'h1{color:rgb(17,34,51)}','scripts/main.js':"document.body.dataset.localScript='ready';",'images/logo.svg':'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="8"><rect width="16" height="8" fill="#ff3300"/></svg>','fonts/demo.woff2':new Uint8Array(await(await fetch('/fonts/InstrumentSans-Variable.woff2')).arrayBuffer())};const htmlPages=await m.buildSitePreviews(htmlFiles,'html');checks.sitePagePaths=Object.keys(htmlPages);const webFrame=document.createElement('iframe');webFrame.sandbox.add('allow-scripts');webFrame.style.cssText='width:640px;height:360px';const webClient=new m.MediaSandboxClient(webFrame);webFrame.src='/media-sandbox.html';document.body.append(webFrame);await webClient.request('website-preview',{html:htmlPages['/'],path:'/'});await new Promise(r=>setTimeout(r,200));checks.websitePreviewMounted=true;webClient.dispose();webFrame.remove();const screenshot=await m.executeMediaJob({kind:'screenshot_site',input:{width:640,height:360}},{document:c.createSite({framework:'html'}),assets:{},siteFiles:htmlFiles});await save({blob:screenshot.files[0].blob,filename:'website-screenshot.png',mimeType:'image/png',warnings:[]});
    const site=c.createSite({framework:'html'});await save(await m.exportProject({document:site,assets:{},format:'zip',filename:'html-site.zip',siteFiles:htmlFiles}));
    const react=c.createSite({framework:'vite-react'});await save(await m.exportProject({document:react,assets:{},format:'zip',filename:'react-site.zip',siteFiles:{'index.html':'<!doctype html><html><head><meta charset="utf-8"></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>','src/main.tsx':"import React from 'react';import{createRoot}from'react-dom/client';createRoot(document.getElementById('root')!).render(<><h1 data-real='react'>Director React production build</h1><img data-public='logo' src='/logo.svg'/></>);",'public/logo.svg':'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="8"><rect width="16" height="8" fill="red"/></svg>'}}));
    let rejected=false;try{await m.exportProject({document:timeline,assets:{},format:'mp4'})}catch(e){rejected=e.name==='MediaRepairError'}checks.missingAssetsRejected=rejected;
    return {formats,checks};
  });
  Object.assign(report,result);
  const website=unzipSync(new Uint8Array(await fs.readFile(path.join(output,'react-site.zip'))));
  for(const [name,bytes]of Object.entries(website)){const filename=path.join(output,'reopened',name);await fs.mkdir(path.dirname(filename),{recursive:true});await fs.writeFile(filename,bytes);}
  const productionServer=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(output,'reopened/dist',pathname==='/'?'index.html':'.'+pathname);if(!file.startsWith(path.join(output,'reopened/dist')+path.sep)){res.writeHead(403);res.end();return;}res.setHeader('content-type',mime[path.extname(file)]??'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(resolve=>productionServer.listen(0,'127.0.0.1',resolve));
  await page.goto(`http://127.0.0.1:${productionServer.address().port}/`);await page.getByRole('heading',{name:'Director React production build'}).waitFor();report.checks.reactZipReopened=true;report.checks.reactPublicImage=await page.locator('[data-public=logo]').evaluate(async img=>{await img.decode();return img.complete&&img.naturalWidth===16;});await page.screenshot({path:path.join(output,'react-zip-reopened.png')});productionServer.close();
  const pdf=await PDFDocument.load(await fs.readFile(path.join(output,'deck.pdf')));report.checks.deckPdfPages=pdf.getPageCount();
  const pptx=unzipSync(new Uint8Array(await fs.readFile(path.join(output,'deck.pptx'))));report.checks.pptxEditableText=new TextDecoder().decode(pptx['ppt/slides/slide1.xml']).includes('Real browser')&&new TextDecoder().decode(pptx['ppt/slides/slide1.xml']).includes('<a:t>export</a:t>');report.checks.pptxMarkdown=new TextDecoder().decode(pptx['ppt/slides/slide2.xml']).includes('<a:buChar')&&new TextDecoder().decode(pptx['ppt/slides/slide2.xml']).includes('b="1"');report.checks.pptxAlpha=new TextDecoder().decode(pptx['ppt/slides/slide2.xml']).includes('<a:alpha val="50000"');report.checks.pptxFont=new TextDecoder().decode(pptx['ppt/slides/slide1.xml']).includes('typeface="Instrument Sans"');report.checks.pptxNotes=new TextDecoder().decode(pptx['ppt/notesSlides/notesSlide1.xml']).includes('Speaker note preserved');
  const hostServer=http.createServer((req,res)=>{res.setHeader('content-type','text/html');res.setHeader('content-security-policy',`default-src 'none';script-src http://127.0.0.1:${port} blob: 'wasm-unsafe-eval';connect-src http://127.0.0.1:${port} data: blob:;worker-src blob:;style-src 'unsafe-inline';img-src data: blob:`);res.end(`<!doctype html><html><head><base href="http://127.0.0.1:${port}/"></head><body><script type="module" src="http://127.0.0.1:${port}/test.js"></script></body></html>`);});await new Promise(resolve=>hostServer.listen(0,'127.0.0.1',resolve));await page.goto(`http://127.0.0.1:${hostServer.address().port}/`);await page.waitForFunction(()=>window.media);report.checks.crossOriginRuntime=await page.evaluate(async()=>{const m=window.media,source=await m.compileComponentSource("import React from 'react';export default ()=> <div>Compiled</div>"),wav=m.encodeWav([Float32Array.from({length:48000},(_,i)=>Math.sin(i/48000*Math.PI*2*440)*.1)],48000);return {baseURI:document.baseURI,origin:location.origin,tsx:source.startsWith('/* @studio/component v1 */'),loudness:await m.measureLoudness(wav,-14)};});hostServer.close();
  for (const file of report.formats.filter((f)=>/\.(mp4|mov|wav|mp3|m4a|flac)$/.test(f.filename))) {
    const probe = await run('ffprobe',['-v','error','-show_format','-show_streams','-of','json',path.join(output,file.filename)]); file.ffprobe=JSON.parse(probe.stdout);
  }
} catch(error) { report.error=String(error); report.stack=error.stack; }
finally { await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2)); await browser.close(); server.close(); }
console.log(JSON.stringify({output,formats:report.formats.map((f)=>({filename:f.filename,bytes:f.bytes})),checks:report.checks,error:report.error,browserErrors:report.browserErrors},null,2));
if(report.error)process.exitCode=1;
