import {build} from 'esbuild';
import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const run=promisify(execFile), studio=fileURLToPath(new URL('../../../',import.meta.url)), dist=path.resolve(studio,'../dist/client');
const out=await fs.mkdtemp(path.join(os.tmpdir(),'director-perception.'));
const rate=16000,fps=25,seconds=8,count=fps*seconds,amplitudes=Array.from({length:count},(_,i)=>.1+.3*((i*73+i*i*31)%101)/100);
const pcm=Float32Array.from({length:rate*seconds},(_,i)=>Math.sin(i/rate*Math.PI*2*370)*amplitudes[Math.floor(i/rate*fps)]);
function wav(values){const bytes=Buffer.alloc(44+values.length*2);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(rate,24);bytes.writeUInt32LE(rate*2,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(values.length*2,40);values.forEach((v,i)=>bytes.writeInt16LE(Math.round(v*32767),44+i*2));return bytes;}
await fs.writeFile(path.join(out,'reference.wav'),wav(pcm));
const pixels=Buffer.alloc(count*32*32*3);for(let frame=0;frame<count;frame++)for(let y=0;y<32;y++)for(let x=0;x<32;x++){const value=x<16?Math.round((frame<6?.1:amplitudes[frame-6])/.4*255):Math.round((.1+.3*((frame*53+frame*frame*11)%97)/96)/.4*255);for(let c=0;c<3;c++)pixels[frame*32*32*3+(y*32+x)*3+c]=value;}
await fs.writeFile(path.join(out,'frames.rgb'),pixels);
await run('ffmpeg',['-v','error','-f','rawvideo','-pix_fmt','rgb24','-s','32x32','-r',String(fps),'-i',path.join(out,'frames.rgb'),'-c:v','libx264','-crf','10','-pix_fmt','yuv420p','-an',path.join(out,'silent.mp4')]);
await run('ffmpeg',['-v','error','-i',path.join(out,'silent.mp4'),'-i',path.join(out,'reference.wav'),'-filter_complex','[1:a]adelay=240:all=1[a]','-map','0:v','-map','[a]','-c:v','copy','-c:a','aac',path.join(out,'delayed.mp4')]);
await build({stdin:{contents:"import * as media from './packages/browser-media/src/index.ts';import * as core from './packages/core/src/index.ts';window.media=media;window.core=core;",resolveDir:studio,sourcefile:'perception-test.ts'},outfile:path.join(out,'test.js'),bundle:true,platform:'browser',format:'esm',target:'chrome140',define:{'process.env.NODE_ENV':'"production"'}});
const worker=(await import(path.resolve(studio,'../dist/server/index.js'))).default;
const types={'.js':'text/javascript','.wasm':'application/wasm','.mp4':'video/mp4','.wav':'audio/wav'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('content-type','text/html');res.end(`<html><head><base href="http://localhost:${server.address().port}/"></head><body><script type="module" src="http://127.0.0.1:${server.address().port}/test.js"></script></body></html>`);return;}const file=url.pathname.startsWith('/runtime/')?path.resolve(dist,'.'+url.pathname):path.resolve(out,'.'+url.pathname);if(!file.startsWith(out+path.sep)&&!file.startsWith(dist+path.sep)){res.writeHead(403);res.end();return;}const bytes=await fs.readFile(file),type=types[path.extname(file)]??'application/octet-stream';if(file.startsWith(dist+path.sep)){const response=await worker.fetch(new Request(`http://localhost:${server.address().port}${url.pathname}`),{ASSETS:{fetch:async()=>new Response(bytes,{headers:{'content-type':type}})}});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}else{res.setHeader('content-type',type);res.setHeader('access-control-allow-origin','*');res.end(bytes);}}catch(e){res.writeHead(404);res.end(String(e));}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage();const report={out,checks:{},errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
try{await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.media&&window.core);
report.checks=await page.evaluate(async()=>{const m=window.media,c=window.core;const source=async name=>(await fetch(name)).blob(),reference=await source('reference.wav');
const audio=await m.checkAvSync(await source('delayed.mp4'),reference,{fps:25,maxLagMs:600});if(audio.method!=='audio'||Math.abs(audio.offsetMs-240)>25||audio.confidence<.2)throw Error('Delayed audio correlation failed '+JSON.stringify(audio));
const motion=await m.checkAvSync(await source('silent.mp4'),reference,{fps:25,maxLagMs:600,roi:{x:0,y:0,width:.5,height:1}});if(motion.method!=='motion'||Math.abs(motion.offsetMs-240)>80||motion.correlation<.7)throw Error('ROI motion correlation failed '+JSON.stringify(motion));
const rate=16000,clicks=new Float32Array(rate*12);for(let beat=0;beat<24;beat++){const accent=beat%4===0;for(let i=0;i<rate*.09;i++){const index=Math.round((beat*.5+.2)*rate)+i;if(index<clicks.length)clicks[index]=Math.sin(i/rate*Math.PI*2*(accent?100:650))*Math.exp(-i/(rate*.012))*(accent?.85:.5);}}
const analysis=await m.analyzeAudioPerception(m.encodeWav([clicks],rate));if(Math.abs(analysis.beats.bpm-120)>5||analysis.beats.beats.length<18||analysis.beats.downbeats.length<4||!Number.isFinite(analysis.beats.confidence))throw Error('Spectral beats failed '+JSON.stringify(analysis.beats));
const timeline=c.createTimeline({fps:25,durationFrames:300}),ops=m.beatMarkerOps(timeline,'ast_perception',analysis.beats,.4);const next=c.applyDocumentOps(timeline,ops,{assetIds:new Set()});if(m.beatMarkerOps(next,'ast_perception',analysis.beats,.4).length!==0)throw Error('Marker retry duplicates');
const ownedAssets={reference:{id:'reference',kind:'audio',url:URL.createObjectURL(reference)},clicks:{id:'clicks',kind:'audio',url:URL.createObjectURL(m.encodeWav([clicks],rate))}};
const cut=await m.executeMediaJob({kind:'cut_audio',input:{assetId:'reference',fromSec:1,toSec:2,handlesSec:.25}},{document:timeline,assets:ownedAssets});const cutProbe=await m.probeMedia(cut.files[0].blob);if(Math.abs(cutProbe.durationMs-1500)>5||cut.result.fromSec!==.75||cut.result.toSec!==2.25||cut.result.contentStartSec!==.25)throw Error('Cut handles were not preserved '+JSON.stringify({result:cut.result,probe:cutProbe}));
const beatJob=await m.executeMediaJob({kind:'analyze_audio',input:{assetId:'clicks',writeMarkers:true,offsetSec:.4}},{document:timeline,assets:ownedAssets});const beatMap=JSON.parse(await beatJob.files[0].blob.text());if(beatJob.result.markerOps.length<18||beatMap.bpm!==120||beatMap.sourceAssetId!=='clicks')throw Error('Beat job output receipt incomplete');
const pre=new AbortController();pre.abort();let preAbort=false;try{await m.checkAvSync(new Blob(),reference,{signal:pre.signal});}catch(e){preAbort=e.name==='AbortError';}if(!preAbort)throw Error('Abort was ignored');
const active=new AbortController(),start=performance.now();let activeAbort=false;let timer;try{await m.withFFmpeg(ff=>{timer=setTimeout(()=>active.abort(),50);return ff.exec(['-f','lavfi','-i','anullsrc','-t','1000','-f','wav','abort.wav']);},active.signal);}catch(e){activeAbort=e.name==='AbortError';}finally{clearTimeout(timer);}if(!activeAbort||performance.now()-start>5000)throw Error('Active codec abort did not finish promptly');
const afterAbort=await m.measureLoudness(reference);if(!Number.isFinite(afterAbort.integratedLufs))throw Error('Codec queue did not recover after abort');
return{crossOriginBaseRuntime:document.baseURI!==location.href,audio,motion,beatAnalysis:{bpm:analysis.beats.bpm,beats:analysis.beats.beats.length,downbeats:analysis.beats.downbeats.length,onsets:analysis.beats.onsets.length,confidence:analysis.beats.confidence,sections:analysis.beats.sections},markers:{count:ops.length,retryDeduplicated:true,firstFrame:next.markers[0].frame,persistentJobOps:beatJob.result.markerOps.length,beatMapFile:true},cut:{...cut.result,durationMs:cutProbe.durationMs},abort:{preAbort,activeAbort,afterAbortLufs:afterAbort.integratedLufs}};});
report.passed=report.errors.length===0;
}catch(e){report.passed=false;report.error=e.stack;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();server.close();}
console.log(JSON.stringify(report,null,2));if(!report.passed)process.exitCode=1;
