import { build } from 'esbuild';
import { build as viteBuild } from 'vite';
import { mkdir, cp, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const here = fileURLToPath(new URL('..', import.meta.url));
const studio = path.resolve(here, '../..');
const root = path.resolve(studio, '..');
const dist = path.join(root, 'dist');
await viteBuild({ configFile: path.join(here, 'vite.config.ts') });
await mkdir(path.join(dist, 'server'), {recursive: true});
await build({ entryPoints: [path.join(here, 'server/worker.ts')], outfile: path.join(dist, 'server/index.js'), bundle: true, platform: 'browser', target: 'es2023', format: 'esm', sourcemap: false, conditions: ['worker', 'browser'] });
await mkdir(path.join(dist, '.openai'), {recursive: true});
await cp(path.join(root, '.openai/hosting.json'), path.join(dist, '.openai/hosting.json'));
await cp(path.join(studio, 'node_modules/@ffmpeg/core/dist/esm'), path.join(dist, 'client/runtime/ffmpeg'), {recursive: true});
await cp(path.join(studio, 'node_modules/esbuild-wasm/esbuild.wasm'), path.join(dist, 'client/runtime/esbuild.wasm'));
await build({entryPoints:[path.join(studio,'node_modules/@ffmpeg/ffmpeg/dist/esm/worker.js')],outfile:path.join(dist,'client/runtime/ffmpeg/worker.js'),bundle:true,format:'esm',platform:'browser',target:'es2023'});
await cp(path.join(here, 'public'), path.join(dist, 'client'), {recursive: true});
await cp(path.join(studio, 'apps/desktop/src/renderer/assets/fonts'), path.join(dist, 'client/fonts'), {recursive: true});
await writeFile(path.join(dist, 'client/fonts/fonts.css'), '@font-face{font-family:"Instrument Sans";src:url("./InstrumentSans-Variable.woff2") format("woff2");font-weight:100 900;font-display:swap}@font-face{font-family:"IBM Plex Mono";src:url("./IBMPlexMono-Regular.woff2") format("woff2");font-display:swap}');
await writeFile(path.join(dist, 'server/wrangler.json'), JSON.stringify({name:'director-studio',main:'index.js',compatibility_date:'2026-09-29',assets:{directory:'../client',binding:'ASSETS',run_worker_first:true},d1_databases:[{binding:'DB',database_name:'director-studio',database_id:'local-preview-db'}],r2_buckets:[{binding:'MEDIA',bucket_name:'director-studio'}]},null,2));
console.log('Native Extension UI and Worker built.');
